// Generated by CoffeeScript 1.3.3
(function() {
  var m;

  m = angular.module("zoomlinks", ['ngResource', 'ui']);

  m.factory('Link', function($resource) {
    return $resource('http://zoomlinks.ru/rest/link/:id');
  });

  m.directive("exportBookmarks", function($timeout) {
    return function(scope, element, attrs) {
      return angular.element(element).click(function() {
        console.log('starting parse bookmarks');
        return chrome.bookmarks.getTree(function(BookmarkTreeNode) {
          return console.log(BookmarkTreeNode);
        });
      });
    };
  });

  m.controller('MainCtr', function($scope, Link) {
    $scope.exportBookmarks = function() {
      return chrome.bookmarks.getTree(function(BookmarkTreeNode) {
        return console.log(BookmarkTreeNode);
      });
    };
    return $scope.exportTabs = function() {
      return chrome.windows.getAll({
        "populate": true
      }, function(tabs) {
        return console.log(tabs);
      });
    };
  });

}).call(this);
